name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    strategy:
      matrix:
        include:
          - os: macos-13
            perl: /usr/bin/perl
            prove: /usr/bin/prove
            cpm-option: --sudo
          - os: macos-13
            perl: /usr/local/bin/perl
            prove: /usr/local/bin/prove
            cpm-option: ''
          - os: macos-latest
            perl: /usr/bin/perl
            prove: /usr/bin/prove
            cpm-option: --sudo
          - os: macos-latest
            perl: /opt/homebrew/bin/perl
            prove: /opt/homebrew/bin/prove
            cpm-option: ''
    name: ${{ matrix.os }} ${{ matrix.perl }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Show environment
        run: |
          uname -a
          sw_vers
          system_profiler SPHardwareDataType
      - name: perl -V
        run: ${{ matrix.perl }} -V
      - name: Install Dependencies
        run: curl -fsSL --compressed https://raw.githubusercontent.com/skaji/cpm/main/cpm | ${{ matrix.perl }} - install -g ${{ matrix.cpm-option }} --with-develop --with-recommends --show-build-log-on-failure
      - name: Build
        run: ${{ matrix.perl }} Makefile.PL && make
      - name: Run Tests
        run: ${{ matrix.prove }} -b t xt
