name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  macos:
    name: macos ${{ matrix.perl }}
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - perl: /usr/bin/perl
            prove: /usr/bin/prove
            cpm-option: --sudo
          - perl: /opt/homebrew/bin/perl
            prove: /opt/homebrew/bin/prove
            cpm-option: ''
    steps:
      - uses: actions/checkout@v4
      - name: perl -V
        run: ${{ matrix.perl }} -V
      - name: Install Dependencies
        run: curl -fsSL --compressed https://raw.githubusercontent.com/skaji/cpm/main/cpm | ${{ matrix.perl }} - install -g ${{ matrix.cpm-option }} --with-configure --with-develop --with-recommends --show-build-log-on-failure
      - name: Build
        run: ${{ matrix.perl }} Build.PL && ./Build
      - name: Run Tests
        run: ${{ matrix.prove }} -b t xt
